### ISSUE TITLE
Comments on Code

### ISSUE THREAD

**Issue by LuminousRedNova** [chernandez7/TwitterParser#2]
I think it was really smart to use a dictionary to store the 3 tweet elements. The only thing that I could possibly add is that maybe you'd want to add something to the code that would allow someone to individual parts from the tweet along side pulling all the information at once.

**Comment by chernandez7** [comment]
That's a good idea, although could you specify a bit? 
Do you mean to see all of the mentions, topics, and links and not have to see all of the tweets? Or what do you have in mind?

**Comment by LuminousRedNova** [comment]
Well in your code you have:

```
public void PrintTweet()
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(_rawTweet);
            Console.WriteLine();
            foreach (var key in _tweet.Keys)
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.Write("{0}: ", key);
                foreach (var value in _tweet[key])
                {
                    Console.ResetColor();
                    Console.Write(" {0}", value);
                    Console.ForegroundColor = ConsoleColor.Yellow;
                }
                Console.WriteLine();
```

Maybe add some additional functions to just call out the the mentions, topics, or URLs on their own rather than forcing all of them for one tweet. For example: it may be useful to see just the topics of a set of tweets to see what is trending or the most mentioned person in a block of so many tweets.

**Comment by chernandez7** [comment]
Added some functionality to sort the dictionary by the frequency of occurrences.

![image](http://i.imgur.com/q7gfBYS.png)
