### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by aviatoali** [chernandez7/TwitterParser#3]
Wow. Very ambitious of you to tackle a GUI and a stream of tweets on such a short deadline. I wasn't even thinking of dealing with a stream yet, let alone an interface. A lot of functionality is elegantly packed into few lines as well, which is always great.

I'd recommend adding some isReply() sort of method that notices if a mention is the first thing in the tweet, in which case it's a reply to someone rather than a regular tweet, and then storing that mention as a special "replyTo" category, denoting that this tweet is a reply to user x.

Also probably wouldn't hurt to refine your Tweet class ProcessLinks method to recognize links to e-mail addresses in tweets as well. Could probably be done by adding in a more general match to just the latter half of your existing regex pattern, then comparing matches against an @-inclusive regex pattern, separating matches to this second search as e-mails and nonmatches to URLs. Would probably also require changing your ProcessMentions to a tighter @-matching regex that ignores e-mails either by having a char prior to the @ symbol, or .com at the end.

**Comment by chernandez7** [comment]
Thanks for the review.

Links now recognize e-mail addresses.
Mentions have been tightened to not do so.

IsReply() has been added as well. I didn't add a special "replyTo" category but when printed out it is differentiated between a non-reply tweet.
